/**
 * EXPORT — the escape hatch. (D9)
 *
 * Hosting is the product; this is the promise that you are not trapped. Note
 * what export is NOT: it is not a second build, and it does not consult the
 * database for content. It zips the artifact that already exists, byte for
 * byte, the same one being served at /s/:slug right now.
 *
 * One release id, three destinations. If export re-rendered anything, "runs
 * anywhere" would be marketing rather than a property.
 */
import archiver from "archiver";
import { PassThrough } from "node:stream";
import { prisma } from "./db";
import { releaseDir } from "./paths";

export type ExportKind = "static" | "container";

export interface ExportBundle {
  filename: string;
  bytes: Buffer;
  releaseId: string;
  versionNo: number;
}

export async function buildExport(releaseId: string, kind: ExportKind): Promise<ExportBundle> {
  const release = await prisma.release.findUnique({
    where: { id: releaseId },
    include: { site: true },
  });
  if (!release) throw new Error("Release not found");
  if (release.status !== "ready") {
    throw new Error(`Release v${release.versionNo} is ${release.status} — there is no artifact to export.`);
  }

  const dir = releaseDir(release.siteId, release.id);
  const archive = archiver("zip", { zlib: { level: 9 } });
  const sink = new PassThrough();
  const chunks: Buffer[] = [];
  sink.on("data", (c: Buffer) => chunks.push(c));
  archive.pipe(sink);

  const stem = `${release.site.slug}-v${release.versionNo}`;

  // The artifact itself — copied, never regenerated.
  archive.directory(dir, kind === "container" ? "site" : false);

  if (kind === "container") {
    archive.append(dockerfile(), { name: "Dockerfile" });
    archive.append(composeFile(release.site.slug), { name: "docker-compose.yml" });
    archive.append(containerReadme(release.site.name, release.versionNo, release.id), {
      name: "README.md",
    });
  } else {
    archive.append(staticReadme(release.site.name, release.versionNo, release.id), {
      name: "README.md",
    });
  }

  const done = new Promise<void>((resolve, reject) => {
    sink.on("end", () => resolve());
    archive.on("error", reject);
  });
  await archive.finalize();
  await done;

  return {
    filename: `${stem}-${kind}.zip`,
    bytes: Buffer.concat(chunks),
    releaseId: release.id,
    versionNo: release.versionNo,
  };
}

/**
 * FAKED: no image is actually built. This is a real, correct Dockerfile that
 * would work — but running `docker build` is left to whoever downloads it.
 */
function dockerfile(): string {
  return `# Generated by the CMS export. Serves one immutable release.
#
# Nothing in this image can render a page. It contains pre-built HTML and a
# static file server, which is the entire claim: the artifact does not need
# the CMS, a database, or Node to run.

FROM nginx:1.27-alpine

COPY site/ /usr/share/nginx/html/

# Directory-style URLs: /about -> /about/index.html
RUN printf '%s\\n' \\
  'server {' \\
  '  listen 80;' \\
  '  root /usr/share/nginx/html;' \\
  '  index index.html;' \\
  '  location / { try_files $uri $uri/ $uri/index.html =404; }' \\
  '}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
`;
}

function composeFile(slug: string): string {
  return `# docker compose up  →  http://localhost:8080
services:
  ${slug}:
    build: .
    ports:
      - "8080:80"
`;
}

function staticReadme(siteName: string, version: number, releaseId: string): string {
  return `# ${siteName} — v${version} (static export)

Release: \`${releaseId}\`

These are the exact files being served by the hosted version of this site. Not
a re-render, not an approximation — the same bytes, copied out of the artifact
directory.

## Run it

Any static host will do. Netlify, S3, GitHub Pages, nginx, \`python -m http.server\`.

You can also just open \`index.html\` directly from your filesystem: the pages
carry their own CSS inline and reference no external assets, so file:// works.

## What still needs the API

The cart. Its JavaScript calls the runtime API baked in at build time — that is
the one thing a static host cannot provide, and exactly the line between
"no server rendered this page" and "this page does nothing".

Everything else is inert HTML and works offline.
`;
}

function containerReadme(siteName: string, version: number, releaseId: string): string {
  return `# ${siteName} — v${version} (container export)

Release: \`${releaseId}\`

\`\`\`bash
docker compose up --build   # → http://localhost:8080
\`\`\`

## What's in here

- \`site/\` — the artifact, identical to the static export and to what the
  hosted URL serves
- \`Dockerfile\` — nginx + those files
- \`docker-compose.yml\` — one command to run it

The image contains no CMS, no database, and no Node runtime. It cannot render a
page, because every page was already rendered when this release was built.

> Note: the CMS generates this bundle but does not build the image for you.
> That's a deliberate scope line in this demo.
`;
}
